### PR TITLE
Rework of Annotations on Android and iOS

### PR DESCRIPTION
**Pull request by charlenni**
I encountered, that Annotations (Polyline and Polygon) don't work. So I changed some parts.

- MapView.Annotations is now a ObservableCollection<Annotation> and monitored from start
- Annotation.Coordinates are a ObservableCollection<Position> and monitored from start
- Polyline now has a StrokeColor, StrokeWidth and Alpha property
- Polygon now has a StrokeColor, StrokeWidth (isn't used in Mapbox up to now), Alpha and FillColor property

Some things are missing up to now:
- A click event for Annotations other than PointAnnotation (see [Mapbox issue #9443](https://github.com/mapbox/mapbox-gl-native/pull/9443))
- Holes for Polygons
- An InfoWindow for Polyline and Polygon

I don't know, if this is the correct way for this changes. If not, write a note and I will change, what isn't correct.

Thank you for your work.

PS: Mapbox 5.1.1 is out :)

### CODE REVIEW

**Comment by charlenni** [comment]
IEnumerable isn't enough. Perhaps a IList is ok, because you want to Add and Remove things to this list. The property itself must be an ObservableCollection and should be readonly.

Why should Annotations not an ObservableCollection? And why should the developer set this property? If Annotations or Coordinates are of type IList, than you could do all things you want. You could Add, Remove and Clear the list. That's ok. Or not?

**Comment by kanvuduc** [comment]
:). From the renderer, you don't need to add/remove or any other kinds of operation on property Annotations . The place you do those things is in your VMs, then you could use whatever kind of collection type you want for the real purpose.

Plz see ListView ItemSource for example.

Cheers.

**Comment by charlenni** [comment]
Ah, I think I get it. You say, the developer is responsible, if she/he wants, that Mapbox tracks changes on the Annotations. If she/he uses an Array there isn't any tracking. If she/he uses an ObservableCollection, than Mapbox tracks any changes. Is this correct?

**Comment by kanvuduc** [comment]
That's right. Our renderer will track the changes if the dev uses ObservableCollection. Otherwise, don't need.

**Comment by kanvuduc** [comment]
I have to close your request due to its out-of-date comparing to our internal changes. 

I tried to merge but I found you still use ObservableCollection even if I suggested to use IEnumerable.

Thanks for your effort.

**Pull request closed without merging**
